[package]
name = "guessgame"
version = "0.1.0"
edition = "2021"
authors = ["james zow <jameszow@163.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"